[tool.poetry]
name = "motor_driver"
version = "0.1.0"
description = ""
authors = ["chris <christopher.sutton12@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
